feat: [SDK-1313] Update Reference Docs to Use Dokka Versioning Plugin (#92)

diff --git a/.github/workflows/generate-docs-site.yml b/.github/workflows/generate-docs-site.yml
--- a/.github/workflows/generate-docs-site.yml
+++ b/.github/workflows/generate-docs-site.yml
@@ -2,11 +2,6 @@ name: Deploy Reference Documentation
 
 on:
   workflow_dispatch:
-    inputs:
-      version:
-        description: 'SDK Version'
-        required: true
-        type: string
 
 permissions:
   id-token: write
@@ -16,70 +11,88 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout "main" Branch
+        uses: actions/checkout@v4
+        with:
+          ref: main
 
-      - uses: actions/setup-java@v4
+      - name: Setup Java 21
+        uses: actions/setup-java@v4
         with:
           distribution: 'corretto'
           java-version: '21'
 
-      - run: mvn -f code dokka:dokka
-
-      - name: Download resources
-        run: |
-          git fetch origin main
-          mkdir -p ${{ runner.temp }}/resources
-          cp .github/workflows/resources/docs-home-template.html ${{ runner.temp }}/resources/docs-home-template.html
-
-      - name: Prepare for deployment
+      - name: Configure Git
         run: |
           git config --global user.email "oss@expediagroup.com"
           git config --global user.name "eg-oss-ci"
-          
-          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
-          
           git fetch --all
-          mkdir -p docs/${{ github.event.inputs.version }}
-          mv code/target/dokka/* docs/${{ github.event.inputs.version }}
-          git add .
-          git commit -m "chore: publishing docs for version ${{ github.event.inputs.version }}"
-          
-          BRANCH_EXISTS=$(git ls-remote --heads origin gh-pages | wc -l)
-          if [ "$BRANCH_EXISTS" -eq 0 ]; then
-            git checkout --orphan gh-pages
-          else
-            git checkout gh-pages
-            git pull origin gh-pages
-          fi
-          
-          git checkout $CURRENT_BRANCH -- docs
-          mv docs/* .
 
-      - name: Build Index Page
+      - name: Checkout "gh-pages" Branch
+        run: git checkout gh-pages
+
+      - name: Extract and Store Latest Live Docs Version Number
+        run: echo "LATEST_DOCS_VERSION=$(jq -r '.version' version.json)" >> $GITHUB_ENV
+
+      - name: Move Latest Docs to the "older" Directory (Archiving latest live release)
         run: |
-          rm -rf docs code
-          touch index.html
-          LIST_ITEMS=""
-          for dir in $(ls -d */ | sort -rV); do
-            if [ "$dir" != "${{ github.event.inputs.version }}/" ] && [ "$dir" != "latest/" ]; then
-              LIST_ITEMS="${LIST_ITEMS}<li><a href=\"${dir}\">${dir}</a></li>"
+          mkdir older/${{ env.LATEST_DOCS_VERSION }} 
+          mv images rapid-sdk scripts styles index.html navigation.html not-found-version.html version.json older/${{ env.LATEST_DOCS_VERSION }}
+
+      - name: Move the "older" Directory to a Temporary Workspace
+        run: mv older ${{ runner.temp }}
+
+      - name: Checkout "main" Branch
+        run: git checkout main
+
+      - name: Generate New Release Reference Docs
+        run: mvn -f code dokka:dokka -Ddokka-old-versions.location=${{ runner.temp }}/older
+
+      - name: Extract and Store Newly Generated Docs Version Number
+        run: echo "NEW_DOCS_VERSION=$(jq -r '.version' code/target/dokka/version.json)" >> $GITHUB_ENV
+
+      - name: Check the New Release Version
+        run: |
+          for dir in ${{ runner.temp }}/older/*; do
+            if [ -d "$dir" ]; then
+              DIR_NAME=$(basename "$dir")
+              if [ "$DIR_NAME" == "${{ env.NEW_DOCS_VERSION }}" ]; then
+                echo "Error: Reference Docs with version ${{env.NEW_DOCS_VERSION }} already exists."
+                echo "Hint: Make sure to update the project version in the pom.xml file"
+                exit 1
+              fi
             fi
           done
-          sed -e "s#{{list_items}}#${LIST_ITEMS}#g" \
-             -e "s#{{latest_version}}#${{ github.event.inputs.version }}#g" \
-             ${{ runner.temp }}/resources/docs-home-template.html > index.html
-          ln -sfn ./${{ github.event.inputs.version }} ./latest 
 
-      - name: Commit
+      - name: Move the Newly Generated Docs to a Temporary Workspace
+        run: mv code/target/dokka ${{ runner.temp }}/${{ env.NEW_DOCS_VERSION }}
+
+      - name: Checkout "gh-pages" Branch
+        run: git checkout gh-pages
+
+      - name: Cleanup Old Docs from the Repository's Root
+        run: rm -rf code images older rapid-sdk scripts styles index.html navigation.html not-found-version.html version.json
+
+      - name: Move Newly Generated Docs to the Repository Root
+        run: mv ${{ runner.temp }}/${{ env.NEW_DOCS_VERSION }}/* .
+
+      - name: Commit the New Release
         run: |
           git add .
-          git commit -m "chore: publishing docs for version ${{ github.event.inputs.version }}"
+          git commit -m "chore: publishing docs for version ${{ env.NEW_DOCS_VERSION }}"
 
       - name: Create Pull Request
         uses: peter-evans/create-pull-request@v6
         with:
           token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
-          commit-message: "chore: publishing docs for version ${{ github.event.inputs.version }}"
-          body: "This PR adds the reference documentation for version ${{ github.event.inputs.version }}."
-          title: "chore: reference docs update for version ${{ github.event.inputs.version }}"
-          branch: "docs-update-${{ github.event.inputs.version }}"
+          commit-message: "chore: publishing docs for version ${{ env.NEW_DOCS_VERSION }}"
+          body: "This PR adds the reference documentation for version ${{ env.NEW_DOCS_VERSION }}."
+          title: "chore: reference docs update for version ${{ env.NEW_DOCS_VERSION }}"
+          branch: "docs-update-${{ env.NEW_DOCS_VERSION }}"
+
+
+
+
+
+
+
